Web_app/Controllers/HomeController.cs
using Web_app.Utilities;
using System.Web.Mvc;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using System.Linq;
using Web_app.Common;
using DataAccess.Repositories;
using Web_app.Models;
using System.Collections.Generic;
using System;
using System.Text;
using DataAccess.Entities;
using Services.Imp;

using System.IO;
using System.Net.Http;
using System.Net;
using System.Net.Http.Headers;
using System.Data;
using System.Threading.Tasks;
using SendGrid;
using SendGrid.Helpers.Mail;
using DailyOpt_CROP4A.Common.Mapper;

namespace Web_app.Controllers
{
    public class HomeController : Controller
    {
        private ConfigRepository _configRepository = null;
        private AdvertisementRepository _advertisementRepository = null;
        private MenuRepository _menuRepository = null;
        private ISanPhamRepository _sanPhamRepository = null;
        public HomeController(ConfigRepository configRepository, AdvertisementRepository advertisementRepository,
            MenuRepository menuRepository, ISanPhamRepository sanPhamRepository)
        {
            _configRepository = configRepository;
            _advertisementRepository = advertisementRepository;
            _menuRepository = menuRepository;
            _sanPhamRepository = sanPhamRepository;
        }
        [HttpGet]
        public ActionResult Index()
        {
            var entiyConfig = _configRepository.GetInfo();
            var model = new ConfigViewModel();
            model.Company = entiyConfig.Company;
            model.SeoKeyWord = entiyConfig.SeoKeyWord;
            model.SeoDesciption = entiyConfig.SeoDesciption;
            model.SeoTitle = entiyConfig.SeoTitle;
            //var title = entiyConfig.SeoTitle != null ? entiyConfig.SeoTitle : entiyConfig.Company;
            //var description = entiyConfig.SeoDesciption != null ? entiyConfig.SeoDesciption : entiyConfig.Company;
            //var key = entiyConfig.SeoKeyWord != null ? entiyConfig.SeoKeyWord : entiyConfig.Company;
            //ViewBag.Title = title;
            //ViewBag.Description = description;
            //ViewBag.Keyword = key;
            return View(model);
        }
        
      
        public ActionResult Footer()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult MenuMobile()
        {
            var entity = _menuRepository.GetByPosition(Constant.POSITION_MENU_TOP);
            return View(entity);
        }
        public ActionResult TimKiem()
        {
            return View();
        }
        public ActionResult Logo()
        {
            var entity = _advertisementRepository.GetByPosition(Constant.POSITION_LOGO);
            return View(entity);
        }

        public ActionResult Menu()
        {
            var entity = _menuRepository.GetByPosition(Constant.POSITION_MENU_TOP);
            return View(entity);
        }
        public ActionResult Social()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult DieuKhoan()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult SocialFooter()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult Slide()
        {
            var entity = _advertisementRepository.GetByPosition(Constant.POSITION_SLIDE);
            return View(entity);
        }
        public ActionResult Codebody()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult CodeHeader()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult PageDetail(string Id)
        {
            var model = _menuRepository.GetByNo(Id);
            return View(model);
        }
        public ActionResult SocialRight()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult FanPage()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        public ActionResult RegisterEmail()
        {
            return View();
        }
        public ActionResult DoiTac()
        {
            var entity = _advertisementRepository.GetByPosition(Constant.POSITION_DOI_TAC);
            return View(entity);
        }
        public ActionResult LienHe()
        {
            var entity = _configRepository.GetInfo();
            return View(entity);
        }
        [HttpPost]
        public ActionResult SendEmail(string email)
        {
            try
            {
                var infoEmailTo = _configRepository.GetInfo().EmailInfo;
                SendMail(null, email, null, null, infoEmailTo);
                return Json(new { result = "Success" });
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        [HttpPost]
        public ActionResult Search(string Keyword)
        {

            var listData = _sanPhamRepository.GetListByName(Keyword);
            var lstModel = SanPhamMapper.ConvertListSanPhamEntityToModel(listData);
            return View(lstModel);
        }
        [HttpPost]
        public ActionResult SendEmailContact(string name, string email, string phone, string message)
        {
            try
            {
                var infoEmailTo = _configRepository.GetInfo().EmailInfo;
                SendMail(name, email, phone, message, infoEmailTo);
                return Json(new { result = "Success" });
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        static async Task SendMail(string name, string email, string phone, string message, string infoEmailTo)
        {
            var apiKey = "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";
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("phamminhson0994@gmail.com", "Chủ nợ");
            var to = new EmailAddress();
            var subject = "";
            var plainTextContent = "";
            var htmlContent = "";

            if (string.IsNullOrEmpty(name))
            {
                subject = "Thông tin người dùng đăng ký trên trang blog cá nhân";
                to = new EmailAddress(infoEmailTo, "Sơn béo");
                htmlContent = "<strong>Email người dùng đăng ký: </strong> " + email + " ";
            }
            else
            {
                subject = "Thông tin người dùng để lại trên trang liên hệ blog cá nhân";
                to = new EmailAddress(infoEmailTo, "Sơn béo");
                htmlContent = "<strong>Họ tên: </strong> " + name + " <br /><strong>Email người dùng đăng ký: </strong> " + email + "<br /><strong>Số điện thoại: </strong> " + email + " <br /><strong>Nội dung: </strong> " + message + "";
            }
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }


    }
}

Web_app/Controllers/SanPhamController.cs
using Web_app.Utilities;
using System.Web.Mvc;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using System.Linq;
using Web_app.Common;
using DataAccess.Repositories;
using Web_app.Models;
using System.Collections.Generic;
using System;
using System.Text;
using DataAccess.Entities;
using Services.Imp;

using System.IO;
using System.Net.Http;
using System.Net;
using System.Net.Http.Headers;
using System.Data;
using System.Threading.Tasks;
using SendGrid;
using SendGrid.Helpers.Mail;
using DailyOpt_CROP4A.Common.Mapper;
using PagedList;

namespace Web_app.Controllers
{
    public class SanPhamController : Controller
    {
        private ConfigRepository _configRepository = null;
        private AdvertisementRepository _advertisementRepository = null;
        private ISanPhamRepository _sanPhamRepository = null;
        private INhomSanPhamRepository _nhomSanPhamRepository = null;
        private IDonHangRepository _donHangRepository = null;
        public SanPhamController(ConfigRepository configRepository, AdvertisementRepository advertisementRepository,
           ISanPhamRepository sanPhamRepository, INhomSanPhamRepository nhomSanPhamRepository, IDonHangRepository donHangRepository)
        {
            _configRepository = configRepository;
            _advertisementRepository = advertisementRepository;
            _sanPhamRepository = sanPhamRepository;
            _nhomSanPhamRepository = nhomSanPhamRepository;
            _donHangRepository = donHangRepository;
        }
        public ActionResult GioHang()
        {
            var lstDatTa = new List<SanPhamViewModel>();
            string[] lstId = null;
            if (Session["GioHang"] != null)
            {
                lstId = Session["GioHang"].ToString().Split(',');
            }
            if (lstId != null)
            {
                var groups = lstId.GroupBy(v => v);
                foreach (var group in groups)
                {
                    var entitySp = _sanPhamRepository.GetByNo(group.Key);
                    entitySp.SoLuong = group.Count().ToString();
                    lstDatTa.Add(SanPhamMapper.ConvertSanPhamEntityToModel(entitySp));
                }
                foreach (var itemsp in lstDatTa)
                {
                    itemsp.NhomSanPham = _nhomSanPhamRepository.GetByNo(itemsp.IdNhomSanPham);
                }
            }
            return View(lstDatTa);
        }
        public ActionResult Set_Gio_Hang(string Id)
        {
            try
            {
                if (Session["GioHang"] != null)
                {
                    Session["GioHang"] = Session["GioHang"].ToString() + "," + Id;
                }
                else
                {
                    Session["GioHang"] = Id;
                }
                return Json(new { Sucsses = "Sucsses" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public ActionResult CapNhat_Gio_Hang(string[] Id)
        {
            try
            {
                var lstId = string.Join(",", Id);
                Session["GioHang"] = null;
                Session["GioHang"] = lstId;
                return Json(new { Sucsses = "Sucsses" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        public ActionResult ThanhToan()
        {
            var lstDatTa = new List<SanPhamViewModel>();
            string[] lstId = null;
            if (Session["GioHang"] != null)
            {
                lstId = Session["GioHang"].ToString().Split(',');
            }
            if (lstId != null)
            {
                var groups = lstId.GroupBy(v => v);
                foreach (var group in groups)
                {
                    var entitySp = _sanPhamRepository.GetByNo(group.Key);
                    entitySp.SoLuong = group.Count().ToString();
                    lstDatTa.Add(SanPhamMapper.ConvertSanPhamEntityToModel(entitySp));
                }
                foreach (var itemsp in lstDatTa)
                {
                    itemsp.NhomSanPham = _nhomSanPhamRepository.GetByNo(itemsp.IdNhomSanPham);
                }
            }
            return View(lstDatTa);
        }
        public ActionResult NhomSanPhamNoiBat()
        {
            var lstEntity = _nhomSanPhamRepository.GetListNoiBat();
            var lstModel = NhomSanPhamMapper.ConvertListNhomSanPhamEntityToModel(lstEntity);
            foreach (var item in lstModel)
            {
                item.lstSanPham = _sanPhamRepository.GetByIdNhom(item.Id.ToString());
            }
            return View(lstModel);
        }

        public ActionResult DanhSachSanPham(int? page, string type)
        {
            int pagesize = 20;
            int pageNumber = (page ?? 1);
            var idNhomSp = _nhomSanPhamRepository.GetIdByUrl(type);
            var lstSanPhamEntity = _sanPhamRepository.GetByIdNhom(idNhomSp.ToString());
            var lstSanPhamModel = SanPhamMapper.ConvertListSanPhamEntityToModel(lstSanPhamEntity);
            foreach (var item in lstSanPhamModel)
            {
                item.NhomSanPham = _nhomSanPhamRepository.GetByNo(item.IdNhomSanPham);
            }
            return View(lstSanPhamModel.ToPagedList(pageNumber, pagesize));
        }
        public ActionResult SanPhamNoiBat()
        {

            var lstSanPhamEntity = _sanPhamRepository.GetTop10();
            var lstSanPhamModel = SanPhamMapper.ConvertListSanPhamEntityToModel(lstSanPhamEntity);
            foreach (var item in lstSanPhamModel)
            {
                item.NhomSanPham = _nhomSanPhamRepository.GetByNo(item.IdNhomSanPham);
            }
            return View(lstSanPhamModel);
        }
        public ActionResult NhomSanPhamTrangChu()
        {
            var lstEntity = _nhomSanPhamRepository.GetListTrangChu();
            var lstModel = NhomSanPhamMapper.ConvertListNhomSanPhamEntityToModel(lstEntity);
            foreach (var item in lstModel)
            {
                item.lstSanPham = _sanPhamRepository.GetByIdNhom(item.Id.ToString());
            }
            return View(lstModel);
        }
        public ActionResult ChiTietSanPham(string url)
        {
            var sanPhamEntity = _sanPhamRepository.GetByUrl(url);
            var sanPhamModel = SanPhamMapper.ConvertSanPhamEntityToModel(sanPhamEntity);
            sanPhamModel.NhomSanPham = _nhomSanPhamRepository.GetByNo(sanPhamEntity.IdNhomSanPham);
            return View(sanPhamModel);
        }
        public ActionResult SanPhamLienQuan(string IdOld, string IdNhom)
        {
            var lstByNhomSp = _sanPhamRepository.GetByIdNhom(IdNhom);
            var lstSanPhamEntity = lstByNhomSp.Where(c => c.Id != int.Parse(IdOld)).ToList();
            var lstSanPhamModel = SanPhamMapper.ConvertListSanPhamEntityToModel(lstSanPhamEntity);
            foreach (var item in lstSanPhamModel)
            {
                item.NhomSanPham = _nhomSanPhamRepository.GetByNo(item.IdNhomSanPham);
            }
            return View(lstSanPhamModel);
        }
        public ActionResult HoanThanhThanhToan(string Ten, string Sdt, string DiaChi, string GhiChu)
        {
            var lstDatTa = new List<SanPhamViewModel>();
            string[] lstId = null;
            var sucsses = false;
            if (Session["GioHang"] != null)
            {
                lstId = Session["GioHang"].ToString().Split(',');
            }
            if (lstId != null)
            {
                var groups = lstId.GroupBy(v => v);
                foreach (var group in groups)
                {
                    var entitySp = _sanPhamRepository.GetByNo(group.Key);
                    entitySp.SoLuong = group.Count().ToString();
                    lstDatTa.Add(SanPhamMapper.ConvertSanPhamEntityToModel(entitySp));
                }
                foreach (var itemsp in lstDatTa)
                {
                    itemsp.NhomSanPham = _nhomSanPhamRepository.GetByNo(itemsp.IdNhomSanPham);
                    var entityDonHang = new DonHangEntity();
                    entityDonHang.LoaiThanhToan = "Thanh toán khi giao hàng";
                    entityDonHang.NgayMua = DateTime.Now;
                    entityDonHang.Sdt = Sdt;
                    entityDonHang.SoLuong = int.Parse(itemsp.SoLuong);
                    entityDonHang.TenKhachHang = Ten;
                    entityDonHang.TenSanPham = itemsp.TenSanPham;
                    entityDonHang.TongGia = itemsp.GiaKhuyenMai != null ? (double.Parse(itemsp.GiaKhuyenMai) * int.Parse(itemsp.SoLuong)) : (double.Parse(itemsp.GiaBan) * int.Parse(itemsp.SoLuong));
                    entityDonHang.DonGia = double.Parse(itemsp.GiaKhuyenMai != null ? itemsp.GiaKhuyenMai : itemsp.GiaBan);
                    entityDonHang.DiaChi = DiaChi;
                    entityDonHang.GhiChu = GhiChu;
                    entityDonHang.Active = false;
                    sucsses = _donHangRepository.Create(entityDonHang);

                    // send email
                    var infoEmailTo = _configRepository.GetInfo().EmailInfo;
                    SendMail(Ten, Sdt, GhiChu, infoEmailTo, itemsp.TenSanPham, itemsp.SoLuong, entityDonHang.TongGia.ToString());
                }
            }
            if (sucsses)
            {
                Session["GioHang"] = null;
                return Json(new { Sucsses = "Sucsses" }, JsonRequestBehavior.AllowGet);
            }
            else { return Json(new { Sucsses = "False" }, JsonRequestBehavior.AllowGet); }

        }
        static async Task SendMail(string name, string phone, string GhiChu, string infoEmailTo, string TenSanPham, string SoLuong ,string TongGia)
        {
            var apiKey = "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";

Web_app/Views/Home/Codebody.cshtml
@using DataAccess.Entities;
@model ConfigEntity
@Html.Raw(Model.CodeAnalytics ?? "")

Web_app/Views/Home/DieuKhoan.cshtml
@using DataAccess.Entities;
@model ConfigEntity
@{
    ViewBag.Img = "http://reviewdiadiemanuong.com/Content/css/logo.png";
    ViewBag.Title = "Điều khoản sử dụng website review địa điểm ăn uống";
    ViewBag.Keyword = "Điều khoản sử dụng website review địa điểm ăn uống";
    ViewBag.Description = "Điều khoản sử dụng website review địa điểm ăn uống";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid disable-text-selection">
    <div class="row">
        <div class="col-12 col-12-mobile">
            <div class="mb-2">
                <h1>
                    <a class="font-weight-bold" href="/">
                        <img class="img-header" src="~/Content/css/ChuHeader.png" /> địa điểm ăn uống
                    </a>
                </h1>
                <p class="sologan"></p>
                <nav class="breadcrumb-container d-sm-block d-lg-inline-block" aria-label="breadcrumb">
                    <ol class="breadcrumb pt-0" style="padding:0">
                        <li class="breadcrumb-item"><a href="/" style="font-weight:bold">Trang chủ</a></li>
                        <li class="breadcrumb-item"><a href="#">Điều khoản sử dụng</a></li>
                    </ol>
                </nav>
            </div>

        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <div class="card mb-4">
                <div class="card-body">
                    <p>@Html.Raw(Model.ContentFooter ?? "")</p>
                </div>
            </div>

        </div>
    </div>
</div>

Web_app/Views/Home/FanPage.cshtml
@using DataAccess.Entities;
@model ConfigEntity
@Html.Raw(Model.FanPage ?? "")

Web_app/Views/Home/Footer.cshtml
@using DataAccess.Entities;
@model ConfigEntity
<section class="section_service">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wraptem">
                    <span class="img"><img src="/Content/project/images/srv_1.png" alt="icon"></span>
                    <div class="content_right">
                        <p>Ưu đãi phí vận chuyển</p>
                        <span>Ưu đãi phí vận chuyển nội thành</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wraptem">
                    <span class="img"><img src="/Content/project/images/srv_2.png" alt="icon"></span>
                    <div class="content_right">
                        <p>Đổi trả hàng</p>
                        <span>Đổi trả hàng nếu hàng lỗi</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wraptem">
                    <span class="img"><img src="/Content/project/images/srv_3.png" alt="icon"></span>
                    <div class="content_right">
                        <p>Tiết kiệm thời gian</p>
                        <span>Nhanh gọn hơn qua online</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="wraptem">
                    <span class="img"><img src="/Content/project/images/srv_4.png" alt="icon"></span>
                    <div class="content_right">
                        <p>Tư vấn trực tiếp</p>
                        <span>Đội ngũ tư vấn nhiệt tình</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<footer class="footer">
    <div class="site-footer">
        <div class="mid-footer">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                        <div class="widget-ft first">
                            <div class="collapse" id="collapseListMenu01">
                                @Html.Raw(Model.GoogleMap ?? "")
                                @*<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29737.184800592768!2d105.7979369044414!3d21.305163577097037!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31351d3b6c7fbed7%3A0xf2ba53a0e97d5260!2zTmFtIFPGoW4sIFPDs2MgU8ahbiwgSMOgIE7hu5lpLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1606805840558!5m2!1svi!2s" width="100%" height="268" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>*@
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
        <div class="bg-footer-bottom copyright clearfix">
            <div class="container">
                <div class="inner clearfix">
                    <div class="row tablet">
                        <div id="copyright" class="col-lg-12 col-md-12 col-sm-12 col-xs-12 a-center fot_copyright">
                            <span class="wsp">
                                <span class="mobile">
                                    &copy; Bản quyền thuộc về <b><a href="https://palletnamson.com/" title="Delta Web" target="_blank">@Model.Company</a></b>
                                    <span class="hidden-xs"> | </span>
                                </span>
                                <span class="opacity1">Hotline</span>
                                <a href="tel:@Model.Hotline" rel="nofollow" title="Pallet Nam Sơn" target="_blank">@Model.Hotline</a>
                            </span>
                        </div>
                    </div>
                </div>
                <a href="#" id="back-to-top" class="backtop" title="Lên đầu trang"><i class="fa fa-angle-up" aria-hidden="true"></i></a>
            </div>
        </div>
    </div>
</footer>
<section class="footer_top">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                <div class="item_f">
                    <h4 class="title-menu">Gọi tư vấn (7h-22h)</h4>
                    <div class="w_f">
                        <i class="fa fa-phone"></i>
                        <a class="fone" href="tel:@Model.Hotline">
                            @Model.Hotline
                        </a>
                    </div>
                    <p>Tất cả các ngày trong tuần</p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                <div class="item_f">
                    <h4 class="title-menu">Gọi khiếu nại (8h-20h)</h4>
                    <div class="w_f">
                        <i class="fa fa-phone"></i>
                        <a class="fone" href="tel:0388287614">
                            @Model.Hotline
                        </a>
                    </div>
                    <p>Các ngày trong tuần (trừ ngày lễ)</p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                <h4 class="title-menu">
                    <span>
                        Nhận ưu đãi ngay
                    </span>
                </h4>
                <ul class="contact contact_mail">
                    <li>
                        @Html.Action("RegisterEmail", "Home")

                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-3 col-lg-3">
                <h4 class="title-menu">
                    <span>
                        Theo dõi ngay
                    </span>
                </h4>
                <ul class="follow_option">
                    <li>
                        <a href="@Model.LinkFace" title="Theo d&otilde;i Facebook Delta Shoes"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li>
                        <a href="@Model.LinkGoogle" title="Theo d&otilde;i Google Plus Delta Shoes"><i class="fa fa-google-plus"></i></a>
                    </li>
                    <li>
                        <a href="#" title="Theo d&otilde;i Instagam Delta Shoes"><i class="fa fa-instagram"></i></a>
                    </li>
                    <li>
                        <a href="@Model.LinkYoutube" title="Theo d&otilde;i Youtube Delta Shoes"><i class="fa fa-youtube-play"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>

Web_app/Views/Home/Index.cshtml
@using Web_app.Models;
@model ConfigViewModel
@{
    ViewBag.Img = "http://reviewdiadiemanuong.com/Content/css/logo.png";
    ViewBag.Title = @HttpUtility.HtmlDecode(Model.SeoTitle != null ? Model.SeoTitle : Model.Company);
    ViewBag.Keyword = @HttpUtility.HtmlDecode(Model.SeoKeyWord != null ? Model.SeoKeyWord : Model.Company);
    ViewBag.Description = @HttpUtility.HtmlDecode(Model.SeoDesciption != null ? Model.SeoKeyWord : Model.Company);
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <script src="~/Content/project/js/main.js"></script>
<script>
    $(window).load(function () {
        $("body").removeClass();
    });
</script>
<!-- Header JS -->
<!--<section class="awe-section-1">
    <section class="section_slider owl_nav_custome2x">
        <div class="home-slider owl-carousel owl-theme owl-carousel-loop not-thuongdq" data-dot="false" data-nav="true" data-loop="true" data-play="true" data-lg-items="1" data-md-items="1" data-sm-items="1" data-xs-items="1" data-margin="0">
            <div class="item">
                <a href="#" class="clearfix">
                    <img src="images/assets-slider_2.jpg" alt="Slider 2">
                </a>
            </div>
        </div>
    </section>
</section>-->
<section class="awe-section-2">
    <section class="section_category">
        <div class="container">
            <div class="wrap">
                <div class="row">
                    @Html.Action("NhomSanPhamNoiBat", "SanPham")
                </div>
            </div>
        </div>
    </section>
</section>
<section class="awe-section-3">
    <section class="section_banchay">
        <div class="container">
            <div class="wrap_bg_in">
                <div class="section title_section_module a-center margin-bottom-20">
                    <h2><a href="san-pham-ban-chay.html" title="S&#7843;n ph&#7849;m b&aacute;n ch&#7841;y">Sản phẩm nổi bật</a></h2>
                </div>
                <div class="section owl_nav_custome2">
                    <div class="owl-carousel " data-dot="false" data-nav="true" data-loop="false" data-play="true" data-lg-items="5" data-md-items="5" data-sm-items="4" data-xs-items="2" data-margin="15">
                        @Html.Action("SanPhamNoiBat", "SanPham")
                    </div>
                </div>
            </div>
        </div>
    </section>
</section>

@Html.Action("NhomSanPhamTrangChu", "SanPham")
<!-- Add to cart -->

<div class="bizweb-product-reviews-module"></div>

Web_app/Views/Home/Logo.cshtml
@using DataAccess.Entities;
@model List<AdvertisementEntity>

@foreach (var item in Model.Take(1))
{
    <a href="/" class="logo-wrapper ">
        <img src="@item.Img" alt="@item.Title">
    </a>
}

Web_app/Views/Home/RegisterEmail.cshtml
<div class="margin-bottom-0">
    <input type="email" id="email" placeholder="Nhập email của bạn">
    <button class="btn btn-primary subscribe" id="btnSubmit" name="subscribe">Đăng ký</button>
    <p id="Mesage" style="color:green; display:none">Cảm ơn bạn đã để lại thông tin!</p>
</div>
<script>
    $('#btnSubmit').click(function (e) {
        var emailTo = $("#email").val();
        if (emailTo != null || emailTo != "") {
            $.ajax({
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                url: '/Home/SendEmail',
                data: JSON.stringify({ email: emailTo }),
                dataType: 'json',
                success: function (result) {
                    if (result.result === "Success") {
                        $("#Mesage").css("display", "block");
                    }
                }
            });
        }
    });
</script>

Web_app/Views/Home/Search.cshtml
@using Web_app.Models;
@model List<SanPhamViewModel>
@{
    ViewBag.Img = "";
    ViewBag.Title = "";
    ViewBag.Keyword ="";
    ViewBag.Description ="";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

ok